export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST" 
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS" 
export const UPDATE_USER_RESET = "UPDATE_USER_RESET" 
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS" 