export const FINANCE_REQUEST = "FINANCE_REQUEST" 
export const FINANCE_SUCCESS = "FINANCE_SUCCESS" 
export const FINANCE_RESET = "FINANCE_RESET" 
export const FINANCE_FAIL = "FINANCE_FAIL"

export const GET_ALL_EXPENSES_REQUEST = "GET_ALL_EXPENSES_REQUEST" 
export const GET_ALL_EXPENSES_SUCCESS = "GET_ALL_EXPENSES_SUCCESS" 
export const GET_ALL_EXPENSES_FAIL = "GET_ALL_EXPENSES_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS" 