export const CREATE_REVENUE_REQUEST = "CREATE_REVENUE_REQUEST" 
export const CREATE_REVENUE_SUCCESS = "CREATE_REVENUE_SUCCESS" 
export const CREATE_REVENUE_RESET = "CREATE_REVENUE_RESET" 
export const CREATE_REVENUE_FAIL = "CREATE_REVENUE_FAIL"