export const CREATE_REVENUE_REQUEST = "CREATE_REVENUE_REQUEST" 
export const CREATE_REVENUE_SUCCESS = "CREATE_REVENUE_SUCCESS" 
export const CREATE_REVENUE_RESET = "CREATE_REVENUE_RESET" 
export const CREATE_REVENUE_FAIL = "CREATE_REVENUE_FAIL"


export const GET_ALL_REVENUE_REQUEST = "GET_ALL_REVENUE_REQUEST" 
export const GET_ALL_REVENUE_SUCCESS = "GET_ALL_REVENUE_SUCCESS" 
export const GET_ALL_REVENUE_FAIL = "GET_ALL_REVENUE_FAIL"